export const paperStyles = {
  position: "relative",
  display: "flex",
  flexDirection: "column",
  minHeight: 400,
  minWidth: 400,
  maxHeight: 600,
  p: 2,
  backgroundColor: "black",
  border: "1px solid lightblue",
  borderRadius: 2,
  overflow: "hidden",
};

export const commentSectionContainerStyles = {
  position: "absolute",
  top: 0,
  left: 0,
  width: "100%",
  height: "100%",
  bgcolor: "#1e1e1e",
  gap: "8px",
  p: 2,
  borderLeft: "1px solid #444",
  overflowY: "auto",
};

export const styles = {
  paper: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    minHeight: 400,
    minWidth: 500,
    maxHeight: 500,
    p: 2,
    backgroundColor: "black",
    border: "1px solid lightblue",
    borderRadius: 2,
    overflow: "hidden",
  },
  commentContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    bgcolor: "black",
    gap: "8px",
    p: 2,
    borderLeft: "1px solid #444",
    overflowY: "auto",
  },
  headerText: {
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    flexShrink: 1,
    minWidth: 0,
    color: "white",
    fontWeight: "bold",
    fontSize: "15px",
  },
  headerContainer: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    minWidth: 0,
    gap: "16px",
    cursor: "pointer",
  },
  divider: {
    backgroundColor: "#444",
  },
  editTextField: {
    width: "100%",
    minRows: 3,
    multiline: true,
    color: "white",
  },
  cancelButton: {
    color: "#ccc",
    border: "1px solid #444",
  },
  saveButton: {
    border: "1px solid lightblue",
    color: "lightblue",
  },
  timestampText: {
    color: "#aaa",
    fontSize: "0.75rem",
    lineHeight: 1,
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  iconActive: { color: "lightblue" },
  iconInactive: { color: "white" },
  editActionsStack: {
    flexDirection: "row",
    gap: 2,
    mt: 1,
    justifyContent: "flex-end",
  },
};
